// Code generated by MockGen. DO NOT EDIT.
// Source: /home/sergey/Go/go-yandex-practicum/internal/workers/metric_agent.go

// Package workers is a generated GoMock package.
package workers

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	types "github.com/sbilibin2017/go-yandex-practicum/internal/types"
)

// MockMetricUpdater is a mock of MetricUpdater interface.
type MockMetricUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockMetricUpdaterMockRecorder
}

// MockMetricUpdaterMockRecorder is the mock recorder for MockMetricUpdater.
type MockMetricUpdaterMockRecorder struct {
	mock *MockMetricUpdater
}

// NewMockMetricUpdater creates a new mock instance.
func NewMockMetricUpdater(ctrl *gomock.Controller) *MockMetricUpdater {
	mock := &MockMetricUpdater{ctrl: ctrl}
	mock.recorder = &MockMetricUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricUpdater) EXPECT() *MockMetricUpdaterMockRecorder {
	return m.recorder
}

// Updates mocks base method.
func (m *MockMetricUpdater) Updates(ctx context.Context, metrics []*types.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Updates", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// Updates indicates an expected call of Updates.
func (mr *MockMetricUpdaterMockRecorder) Updates(ctx, metrics interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Updates", reflect.TypeOf((*MockMetricUpdater)(nil).Updates), ctx, metrics)
}
