// Code generated by MockGen. DO NOT EDIT.
// Source: /home/sergey/Go/go-yandex-practicum/internal/workers/metric_agent.go

// Package workers is a generated GoMock package.
package workers

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	types "github.com/sbilibin2017/go-yandex-practicum/internal/types"
)

// MockMetricFacade is a mock of MetricFacade interface.
type MockMetricFacade struct {
	ctrl     *gomock.Controller
	recorder *MockMetricFacadeMockRecorder
}

// MockMetricFacadeMockRecorder is the mock recorder for MockMetricFacade.
type MockMetricFacadeMockRecorder struct {
	mock *MockMetricFacade
}

// NewMockMetricFacade creates a new mock instance.
func NewMockMetricFacade(ctrl *gomock.Controller) *MockMetricFacade {
	mock := &MockMetricFacade{ctrl: ctrl}
	mock.recorder = &MockMetricFacadeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricFacade) EXPECT() *MockMetricFacadeMockRecorder {
	return m.recorder
}

// Update mocks base method.
func (m *MockMetricFacade) Update(ctx context.Context, metric types.MetricUpdatePathRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, metric)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMetricFacadeMockRecorder) Update(ctx, metric interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMetricFacade)(nil).Update), ctx, metric)
}
