// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: metric_update.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetricUpdater_Updates_FullMethodName = "/go_yandex_practicum.MetricUpdater/Updates"
)

// MetricUpdaterClient is the client API for MetricUpdater service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricUpdaterClient interface {
	Updates(ctx context.Context, in *UpdateMetricsRequest, opts ...grpc.CallOption) (*UpdateMetricsResponse, error)
}

type metricUpdaterClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricUpdaterClient(cc grpc.ClientConnInterface) MetricUpdaterClient {
	return &metricUpdaterClient{cc}
}

func (c *metricUpdaterClient) Updates(ctx context.Context, in *UpdateMetricsRequest, opts ...grpc.CallOption) (*UpdateMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMetricsResponse)
	err := c.cc.Invoke(ctx, MetricUpdater_Updates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricUpdaterServer is the server API for MetricUpdater service.
// All implementations must embed UnimplementedMetricUpdaterServer
// for forward compatibility.
type MetricUpdaterServer interface {
	Updates(context.Context, *UpdateMetricsRequest) (*UpdateMetricsResponse, error)
	mustEmbedUnimplementedMetricUpdaterServer()
}

// UnimplementedMetricUpdaterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetricUpdaterServer struct{}

func (UnimplementedMetricUpdaterServer) Updates(context.Context, *UpdateMetricsRequest) (*UpdateMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Updates not implemented")
}
func (UnimplementedMetricUpdaterServer) mustEmbedUnimplementedMetricUpdaterServer() {}
func (UnimplementedMetricUpdaterServer) testEmbeddedByValue()                       {}

// UnsafeMetricUpdaterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricUpdaterServer will
// result in compilation errors.
type UnsafeMetricUpdaterServer interface {
	mustEmbedUnimplementedMetricUpdaterServer()
}

func RegisterMetricUpdaterServer(s grpc.ServiceRegistrar, srv MetricUpdaterServer) {
	// If the following call pancis, it indicates UnimplementedMetricUpdaterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetricUpdater_ServiceDesc, srv)
}

func _MetricUpdater_Updates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricUpdaterServer).Updates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricUpdater_Updates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricUpdaterServer).Updates(ctx, req.(*UpdateMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetricUpdater_ServiceDesc is the grpc.ServiceDesc for MetricUpdater service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetricUpdater_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "go_yandex_practicum.MetricUpdater",
	HandlerType: (*MetricUpdaterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Updates",
			Handler:    _MetricUpdater_Updates_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metric_update.proto",
}
