// Code generated by MockGen. DO NOT EDIT.
// Source: /home/sergey/Go/go-yandex-practicum/internal/handlers/metric_update_body.go

// Package handlers is a generated GoMock package.
package handlers

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	types "github.com/sbilibin2017/go-yandex-practicum/internal/types"
)

// MockMetricUpdateBodyService is a mock of MetricUpdateBodyService interface.
type MockMetricUpdateBodyService struct {
	ctrl     *gomock.Controller
	recorder *MockMetricUpdateBodyServiceMockRecorder
}

// MockMetricUpdateBodyServiceMockRecorder is the mock recorder for MockMetricUpdateBodyService.
type MockMetricUpdateBodyServiceMockRecorder struct {
	mock *MockMetricUpdateBodyService
}

// NewMockMetricUpdateBodyService creates a new mock instance.
func NewMockMetricUpdateBodyService(ctrl *gomock.Controller) *MockMetricUpdateBodyService {
	mock := &MockMetricUpdateBodyService{ctrl: ctrl}
	mock.recorder = &MockMetricUpdateBodyServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricUpdateBodyService) EXPECT() *MockMetricUpdateBodyServiceMockRecorder {
	return m.recorder
}

// Update mocks base method.
func (m *MockMetricUpdateBodyService) Update(ctx context.Context, metrics []types.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMetricUpdateBodyServiceMockRecorder) Update(ctx, metrics interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMetricUpdateBodyService)(nil).Update), ctx, metrics)
}
