// Code generated by MockGen. DO NOT EDIT.
// Source: /home/sergey/Go/go-yandex-practicum/internal/handlers/metric_updates_body.go

// Package handlers is a generated GoMock package.
package handlers

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	types "github.com/sbilibin2017/go-yandex-practicum/internal/types"
)

// MockMetricUpdatesBodyService is a mock of MetricUpdatesBodyService interface.
type MockMetricUpdatesBodyService struct {
	ctrl     *gomock.Controller
	recorder *MockMetricUpdatesBodyServiceMockRecorder
}

// MockMetricUpdatesBodyServiceMockRecorder is the mock recorder for MockMetricUpdatesBodyService.
type MockMetricUpdatesBodyServiceMockRecorder struct {
	mock *MockMetricUpdatesBodyService
}

// NewMockMetricUpdatesBodyService creates a new mock instance.
func NewMockMetricUpdatesBodyService(ctrl *gomock.Controller) *MockMetricUpdatesBodyService {
	mock := &MockMetricUpdatesBodyService{ctrl: ctrl}
	mock.recorder = &MockMetricUpdatesBodyServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricUpdatesBodyService) EXPECT() *MockMetricUpdatesBodyServiceMockRecorder {
	return m.recorder
}

// Updates mocks base method.
func (m *MockMetricUpdatesBodyService) Updates(ctx context.Context, metrics []*types.Metrics) ([]*types.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Updates", ctx, metrics)
	ret0, _ := ret[0].([]*types.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Updates indicates an expected call of Updates.
func (mr *MockMetricUpdatesBodyServiceMockRecorder) Updates(ctx, metrics interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Updates", reflect.TypeOf((*MockMetricUpdatesBodyService)(nil).Updates), ctx, metrics)
}
