// Code generated by MockGen. DO NOT EDIT.
// Source: /home/sergey/Go/go-yandex-practicum/internal/handlers/metric_value_body.go

// Package handlers is a generated GoMock package.
package handlers

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	types "github.com/sbilibin2017/go-yandex-practicum/internal/types"
)

// MockMetricGetBodyService is a mock of MetricGetBodyService interface.
type MockMetricGetBodyService struct {
	ctrl     *gomock.Controller
	recorder *MockMetricGetBodyServiceMockRecorder
}

// MockMetricGetBodyServiceMockRecorder is the mock recorder for MockMetricGetBodyService.
type MockMetricGetBodyServiceMockRecorder struct {
	mock *MockMetricGetBodyService
}

// NewMockMetricGetBodyService creates a new mock instance.
func NewMockMetricGetBodyService(ctrl *gomock.Controller) *MockMetricGetBodyService {
	mock := &MockMetricGetBodyService{ctrl: ctrl}
	mock.recorder = &MockMetricGetBodyServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricGetBodyService) EXPECT() *MockMetricGetBodyServiceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockMetricGetBodyService) Get(ctx context.Context, metricID types.MetricID) (*types.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, metricID)
	ret0, _ := ret[0].(*types.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockMetricGetBodyServiceMockRecorder) Get(ctx, metricID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockMetricGetBodyService)(nil).Get), ctx, metricID)
}
